# Generated by Django 5.2.9 on 2026-04-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_cartitem_is_active_favorite_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_active',
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons/', verbose_name='Иконка'),
        ),
    ]
